version: "3.9"

services:
  dev_api:
    container_name: dev_api
    build: .
    command: bash -c "alembic upgrade head && python3 main.py"
    env_file:
      - env/dev.env
    ports:
      - "8000:8000"