version: "3.9"

services:
  local_api:
    container_name: local_api
    build: .
    command: bash -c "alembic upgrade head && python3 main.py"
    env_file:
      - env/local.env
    ports:
      - "8000:8000"
    depends_on:
      - db-test

  db-test:
    image: postgres:latest
    container_name: db_test
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres